spring.datasource.url=jdbc:mysql://localhost:3306/todo_app
spring.datasource.username=root
spring.datasource.password=159411

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080